#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eric-oss-app-lcm.name" . }}-log-config
  labels:
    {{- include "eric-oss-app-lcm.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-oss-app-lcm.annotations" . | nindent 4 }}
data:
  logcontrol.json: |
    [
      {
        "container": {{ include "eric-oss-app-lcm.name" . | quote }},
        "severity": "info"
      }
    ]