/*******************************************************************************
 * COPYRIGHT Ericsson 2021
 *
 *
 *
 * The copyright to the computer program(s) herein is the property of
 *
 * Ericsson Inc. The programs may be used and/or copied only with written
 *
 * permission from Ericsson Inc. or in accordance with the terms and
 *
 * conditions stipulated in the agreement/contract under which the
 *
 * program(s) have been supplied.
 ******************************************************************************/

package com.ericsson.oss.ae.repositories;

import static org.assertj.core.api.AssertionsForInterfaceTypes.assertThat;

import java.util.Arrays;
import java.util.List;

import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.EntityTransaction;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.transaction.annotation.Transactional;

import com.ericsson.oss.ae.model.entity.AppInstance;

@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_CLASS)
@ExtendWith(SpringExtension.class)
@SpringBootTest
public class AppInstanceRepositoryTest {

    @Autowired
    AppInstanceRepository objectUnderTest;

    @Autowired
    EntityManagerFactory entityManagerFactory;

    @BeforeEach
    void resetRepositoryAutoGeneratedIdForAppInstanceRepository() {
        final EntityManager entityManager = entityManagerFactory.createEntityManager();

        final EntityTransaction entityTransaction = entityManager.getTransaction();
        entityTransaction.begin();
        entityManager.createNativeQuery("ALTER TABLE app_instance ALTER COLUMN id RESTART WITH 1").executeUpdate();
        entityTransaction.commit();
    }

    @Transactional
    @Test
    public void givenAValidAppInstanceObject_WhenSavingAppInstanceToDatabase_ThenAppInstancePersistedInDbWithCorrectData() {
        objectUnderTest.save(AppInstance.builder().appOnBoardingAppId(2L).build());

        final AppInstance actualAppInstance = objectUnderTest.findById(1L).orElse(null);

        assertThat(actualAppInstance).isNotNull();
        assertThat(actualAppInstance.getId()).isEqualTo(1L);
        assertThat(actualAppInstance.getAppOnBoardingAppId()).isEqualTo(2L);
    }

    @Transactional
    @Test
    public void givenDatabaseContainsValidAppInstances_WhenFindingAllAppInstances_ThenReturnAllPersistedAppInstancesWithCorrectData() {
        objectUnderTest.saveAll(Arrays.asList(AppInstance.builder().appOnBoardingAppId(4L).build(),
                AppInstance.builder().appOnBoardingAppId(5L).build(), AppInstance.builder().appOnBoardingAppId(6L).build()));

        final List<AppInstance> actualAppInstances = objectUnderTest.findAll();

        assertThat(actualAppInstances.get(0).getId()).isEqualTo(1L);
        assertThat(actualAppInstances.get(0).getAppOnBoardingAppId()).isEqualTo(4L);
        assertThat(actualAppInstances.get(1).getId()).isEqualTo(2L);
        assertThat(actualAppInstances.get(1).getAppOnBoardingAppId()).isEqualTo(5L);
        assertThat(actualAppInstances.get(2).getId()).isEqualTo(3L);
        assertThat(actualAppInstances.get(2).getAppOnBoardingAppId()).isEqualTo(6L);
    }

    @Transactional
    @Test
    public void givenDatabaseContainsNoAppInstances_WhenFindingAppInstanceById_ThenRepositoryReturnsNull() {
        final AppInstance actualAppInstance = objectUnderTest.findById(1L).orElse(null);

        assertThat(actualAppInstance).isNull();
    }

    @Transactional
    @Test
    public void givenDatabaseContainsNoAppInstances_WhenFindingAllAppInstances_ThenReturnAppInstanceListOfSizeZero() {
        assertThat(objectUnderTest.findAll().size()).isZero();
    }

    @Transactional
    @Test
    public void givenDatabaseContainsASingleAppInstance_WhenDeleteAppInstanceById_ThenDatabaseContainsNoPersistedAppInstances() {
        objectUnderTest.save(AppInstance.builder().appOnBoardingAppId(2L).build());
        assertThat(objectUnderTest.findAll().size()).isOne();

        objectUnderTest.deleteById(1L);
        assertThat(objectUnderTest.findAll().size()).isZero();
    }
}
