#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

#Metrics related configurations
management.endpoint.metrics.enabled: "true"
management.endpoints.web.exposure.include: "*"
management.endpoint.prometheus.enabled: "true"
management.metrics.export.prometheus.enabled: "true"
management.metrics.web.server.request.autotime.enabled: "true"
management.info.env.enabled: "true"

#opentracing.jaeger.enabled: "true"
#Tracing properties
management.tracing.propagation.produce: ${ERIC_PROPAGATOR_PRODUCE:[B3]}
otel.exporter.otlp.traces.protocol: ${OTEL_EXPORTER_OTLP_TRACES_PROTOCOL:grpc}
spring.application.name: ${SERVICE_ID:eric-oss-app-lcm}

endpoints.health.sensitive: "false"
info.app.name: '@name@'
info.app.description: Application lcm
info.app.version: '@version@'
info.app.legal: "COPYRIGHT Ericsson 2021 -
 The copyright to the computer program(s) herein is the property of
 Ericsson Inc. The programs may be used and/or copied only with written
 permission from Ericsson Inc. or in accordance with the terms and
 conditions stipulated in the agreement/contract under which the
 program(s) have been supplied."

#See more details about pattern layout: https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/PatternLayout.html
#See more details about logging.pattern.level : https://docs.spring.io/spring-boot/docs/2.4.2/reference/html/spring-boot-features.html#boot-features-custom-log-configuration
#logging.pattern.level: "%5p [%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}][%X{userName}]"

#Set the stubrunner credentials:
#stubrunner.username: <LAN SIGNUM ID>
#stubrunner.password: <LAN encrypted PWD or JFrog API Key>
stubrunner.username: ${SELI_ARTIFACTORY_REPO_USER}
stubrunner.password: ${SELI_ARTIFACTORY_REPO_PASS}

monitoringJob.fixedRate.in.milliseconds: 30000
monitoringJob.initialDelay.in.milliseconds: 30000

deletionJob.fixedRate.in.milliseconds: 30000
deletionJob.initialDelay.in.milliseconds: 20000

spring.flyway.baseline-on-migrate: true
spring.flyway.enabled: false

logging:
  config: ${LOGBACK_CONFIG_FILE:classpath:logback-json.xml}

frontEnd:
  corsValue: ${CORS_VALUE:#{'CORS_VALUE'}}

# Values specific to the com.ericsson.oss.ae.acm package.

# Default scheduling times and timeout for the InitializeAppMonitoringJob class.
initializeAppMonitoringJob.schedulingRate.in.milliseconds: 30000
initializeAppMonitoringJob.delayRate.in.milliseconds: 10000
initializeAppUseCase.timeout.in.milliseconds: 3000000000

# Default scheduling times and timeout for the DeinitializeAppMonitoringJob class.
deinitializeAppMonitoringJob.schedulingRate.in.milliseconds: 30000
deinitializeAppMonitoringJob.delayRate.in.milliseconds: 10000
deinitializeAppUseCase.timeout.in.milliseconds: 3000000000

# Default scheduling times and timeout for the UndeployAppInstanceMonitoringJob class.
undeployAppInstanceMonitoringJob.schedulingRate.in.milliseconds: 30000
undeployAppInstanceMonitoringJob.delayRate.in.milliseconds: 10000
undeployAppInstanceUseCase.timeout.in.milliseconds: 3000000000

# Default scheduling times and timeout for the DeployAppInstanceMonitoringJob class.
deployAppInstanceMonitoringJob.schedulingRate.in.milliseconds: 30000
deployAppInstanceMonitoringJob.delayRate.in.milliseconds: 10000
deployAppInstanceUseCase.timeout.in.milliseconds: 3000000000

# Default scheduling times and timeout for the UpgradeAppInstanceMonitoringJob class.
upgradeAppInstanceMonitoringJob.schedulingRate.in.milliseconds: 30000
upgradeAppInstanceMonitoringJob.delayRate.in.milliseconds: 10000
upgradeAppInstanceUseCase.timeout.in.milliseconds: 3000000000

# Default scheduling times and timeout for the UpdateAppInstanceMonitoringJob class.
updateAppInstanceMonitoringJob.schedulingRate.in.milliseconds: 30000
updateAppInstanceMonitoringJob.delayRate.in.milliseconds: 10000
updateAppInstanceUseCase.timeout.in.milliseconds: 3000000000

# Default scheduling times and timeout for the DeleteAppInstanceMonitoringJob class.
deleteAppInstanceMonitoringJob.schedulingRate.in.milliseconds: 30000
deleteAppInstanceMonitoringJob.delayRate.in.milliseconds: 10000
deleteAppInstanceUseCase.timeout.in.milliseconds: 3000000000

object-store:
  hostname: ${OBJECT_STORE_HOSTNAME:eric-data-object-storage-mn}
  port: 9000
  credentials:
    username: ${OBJECT_STORE_USERNAME:default}
    password: ${OBJECT_STORE_PASSWORD:default}

ericsson:
  logging:
    runtime-level-control:
      enabled: ${RUN_TIME_LEVEL_CONTROL:false}
  tracing:
    enabled: ${ERIC_TRACING_ENABLED:true}
    polingInterval: ${ERIC_TRACING_POLING_INTERVAL:30}
    exporter:
      endpoint: ${ERIC_EXPORTER_ENDPOINT:http://eric-dst-collector:4317}
      protocol: ${ERIC_EXPORTER_PROTOCOL:grpc}
    sampler:
      jaeger_remote:
        endpoint: ${ERIC_SAMPLER_JAEGER_REMOTE_ENDPOINT:http://eric-dst-collector:14250}
    endpoints:
      exclude: /actuator/prometheus, /actuator/health,/ping, /metric

audit-log:
  include-pattern:
    - "/app-lcm/v1/**"
    - "/v3/**"