#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{ $serviceMesh := include "eric-oss-app-lcm.service-mesh-enabled" . | trim }}
{{ $tls := include "eric-oss-app-lcm.global-security-tls-enabled" . | trim }}
{{ if and (eq $serviceMesh "true") (eq $tls "true") }}
apiVersion: siptls.sec.ericsson.com/v1
kind: InternalCertificate
metadata:
  name: {{ include "eric-oss-app-lcm.name" . }}-appmgr-data-document-db-int-cert
  labels:
  {{- include "eric-oss-app-lcm.helmK8s-labels" .| nindent 4 }}
  annotations:
  {{- include "eric-oss-app-lcm.product-info" .| nindent 4 }}
spec:
  kubernetes:
    generatedSecretName: {{ include "eric-oss-app-lcm.name" . }}-data-pg-db-secret
    certificateName: "cert.pem"
    privateKeyName: "key.pem"
  certificate:
    subject:
      cn: {{ include "eric-oss-app-lcm.dbuser" . }}
    issuer:
      reference: {{ index .Values "eric-data-document-db" "name" }}-client-ca
    extendedKeyUsage:
      tlsClientAuth: true
      tlsServerAuth: false
{{ end }}
