#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- if (include "eric-oss-app-lcm.securityPolicy.rolekind"  . ) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "eric-oss-app-lcm.securityPolicy-rolebinding-name" . }}
  labels:
{{- include "eric-oss-app-lcm.labels" . | nindent 4 }}
  annotations:
{{- include "eric-oss-app-lcm.annotations" . | nindent 4 }}
{{- include "eric-oss-app-lcm.securityPolicy.annotations" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ template "eric-oss-app-lcm.securityPolicy.rolekind" . }}
  name: {{ template "eric-oss-app-lcm.securityPolicy.rolename" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "eric-oss-app-lcm.serviceAccountName" . }}
{{- else -}}
   {{- if .Values.global -}}
     {{- if .Values.global.security -}}
       {{- if .Values.global.security.policyBinding -}}
         {{- if .Values.global.security.policyBinding.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "eric-oss-app-lcm.name" . }}-security-policy
  labels:
{{- include "eric-oss-app-lcm.labels" . | nindent 4 }}
  annotations:
{{- include "eric-oss-app-lcm.annotations" . | nindent 4 }}
{{- include "eric-oss-app-lcm.securityPolicy.annotations" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "eric-oss-app-lcm.securityPolicy.reference" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "eric-oss-app-lcm.name" . }}
        {{- end -}}
      {{- end -}}
    {{- end -}}
  {{- end -}}
{{- end -}}

