#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{ $serviceMesh := include "eric-oss-app-lcm.service-mesh-enabled" . | trim }}
{{ $tls := include "eric-oss-app-lcm.global-security-tls-enabled" . | trim }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eric-oss-app-lcm.fullname" . }}
  labels:
  {{- include "eric-oss-app-lcm.labels" . | nindent 4 }}
  annotations:
  {{- include "eric-oss-app-lcm.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | quote }}
{{- if .Values.global }}
  {{- if .Values.global.internalIPFamily }}
  ipFamilies: [{{ .Values.global.internalIPFamily }}]
  {{- end }}
{{- end }}
  ports:
    - name: http-backend
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    - name: https-frontend
      port: {{ .Values.service.frontendPort }}
      targetPort: {{ if and (eq $serviceMesh "true") (eq $tls "true") }}8443{{ else }}frontend-http{{ end }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "eric-oss-app-lcm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

