{{- if .Values.global -}}
{{- if and .Values.global.networkPolicy .Values.networkPolicy -}}
{{- if and .Values.global.networkPolicy.enabled .Values.networkPolicy.enabled -}}

#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "eric-oss-app-lcm.name" . }}-bragent-policy
  labels:
    {{- include "eric-oss-app-lcm.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-oss-app-lcm.annotations" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "eric-oss-app-lcm.name" . }}-data-bragent
  policyTypes:
    - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ include "eric-oss-app-lcm.name" . }}-data
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: eric-ctrl-bro
    ports:
    - protocol: TCP
      port: 8083
{{- end }}
{{- end }}
{{- end }}
