{{- if .Release.IsUpgrade -}}
{{- if eq (include "eric-oss-app-lcm.dbSecretName" .) .Chart.Name -}}
{{- if .Values.global -}}
{{- if and .Values.global.networkPolicy .Values.networkPolicy -}}
{{- if and .Values.global.networkPolicy.enabled .Values.networkPolicy.enabled -}}

#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "eric-oss-app-lcm.name" . }}-change-pg-creds-policy
  labels:
    {{- include "eric-oss-app-lcm.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-11"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- include "eric-oss-app-lcm.annotations" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: eric-oss-app-lcm-data
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            job-name: {{ include "eric-oss-app-lcm.name" . }}-change-db-creds-hook
      ports:
        - protocol: TCP
          port: 5432
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}